name: Dockerhub Deploy

on: push

jobs:
    curl:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: thunderspike/645_assignment3_middleware:latest

            - name: Github Action for curl
              uses: wei/curl@v1.1.1
              with:
                  args: >
                      -k
                      -u "${{ secrets.RANCHER_TOKEN }}"
                      -X POST
                      -H 'Accept: application/json'
                      -H 'Content-Type: application/json'
                      https://ec2-34-238-190-146.compute-1.amazonaws.com/v3/project/c-v88j4:p-qt2gf/workloads/statefulset:default:middleware?action=redeploy
